/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CabangLombaRouteImport } from './routes/cabang-lomba'
import { Route as IndexRouteImport } from './routes/index'

const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CabangLombaRoute = CabangLombaRouteImport.update({
  id: '/cabang-lomba',
  path: '/cabang-lomba',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabang-lomba': typeof CabangLombaRoute
  '/faq': typeof FaqRoute
  '/jadwal': typeof JadwalRoute
  '/kontak': typeof KontakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabang-lomba': typeof CabangLombaRoute
  '/faq': typeof FaqRoute
  '/jadwal': typeof JadwalRoute
  '/kontak': typeof KontakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabang-lomba': typeof CabangLombaRoute
  '/faq': typeof FaqRoute
  '/jadwal': typeof JadwalRoute
  '/kontak': typeof KontakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cabang-lomba' | '/faq' | '/jadwal' | '/kontak'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cabang-lomba' | '/faq' | '/jadwal' | '/kontak'
  id: '__root__' | '/' | '/cabang-lomba' | '/faq' | '/jadwal' | '/kontak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabangLombaRoute: typeof CabangLombaRoute
  FaqRoute: typeof FaqRoute
  JadwalRoute: typeof JadwalRoute
  KontakRoute: typeof KontakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabang-lomba': {
      id: '/cabang-lomba'
      path: '/cabang-lomba'
      fullPath: '/cabang-lomba'
      preLoaderRoute: typeof CabangLombaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabangLombaRoute: CabangLombaRoute,
  FaqRoute: FaqRoute,
  JadwalRoute: JadwalRoute,
  KontakRoute: KontakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
