/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CabangLombaRouteImport } from './routes/cabang-lomba'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanitiaIndexRouteImport } from './routes/panitia.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BaganIndexRouteImport } from './routes/bagan.index'
import { Route as PanitiaStatistikRouteImport } from './routes/panitia.statistik'
import { Route as PanitiaSetupRouteImport } from './routes/panitia.setup'
import { Route as PanitiaSertifikatRouteImport } from './routes/panitia.sertifikat'
import { Route as PanitiaNpsnToolsRouteImport } from './routes/panitia.npsn-tools'
import { Route as PanitiaIdcardRouteImport } from './routes/panitia.idcard'
import { Route as PanitiaGaleriRouteImport } from './routes/panitia.galeri'
import { Route as PanitiaBracketRouteImport } from './routes/panitia.bracket'
import { Route as DashboardProfilRouteImport } from './routes/dashboard.profil'
import { Route as BaganSlugRouteImport } from './routes/bagan.$slug'
import { Route as DashboardPendaftaranIndexRouteImport } from './routes/dashboard.pendaftaran.index'
import { Route as DashboardPendaftaranBaruRouteImport } from './routes/dashboard.pendaftaran.baru'
import { Route as DashboardPendaftaranIdRouteImport } from './routes/dashboard.pendaftaran.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CabangLombaRoute = CabangLombaRouteImport.update({
  id: '/cabang-lomba',
  path: '/cabang-lomba',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanitiaIndexRoute = PanitiaIndexRouteImport.update({
  id: '/panitia/',
  path: '/panitia/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaganIndexRoute = BaganIndexRouteImport.update({
  id: '/bagan/',
  path: '/bagan/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanitiaStatistikRoute = PanitiaStatistikRouteImport.update({
  id: '/panitia/statistik',
  path: '/panitia/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const PanitiaSetupRoute = PanitiaSetupRouteImport.update({
  id: '/panitia/setup',
  path: '/panitia/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PanitiaSertifikatRoute = PanitiaSertifikatRouteImport.update({
  id: '/panitia/sertifikat',
  path: '/panitia/sertifikat',
  getParentRoute: () => rootRouteImport,
} as any)
const PanitiaNpsnToolsRoute = PanitiaNpsnToolsRouteImport.update({
  id: '/panitia/npsn-tools',
  path: '/panitia/npsn-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PanitiaIdcardRoute = PanitiaIdcardRouteImport.update({
  id: '/panitia/idcard',
  path: '/panitia/idcard',
  getParentRoute: () => rootRouteImport,
} as any)
const PanitiaGaleriRoute = PanitiaGaleriRouteImport.update({
  id: '/panitia/galeri',
  path: '/panitia/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const PanitiaBracketRoute = PanitiaBracketRouteImport.update({
  id: '/panitia/bracket',
  path: '/panitia/bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfilRoute = DashboardProfilRouteImport.update({
  id: '/dashboard/profil',
  path: '/dashboard/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const BaganSlugRoute = BaganSlugRouteImport.update({
  id: '/bagan/$slug',
  path: '/bagan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPendaftaranIndexRoute =
  DashboardPendaftaranIndexRouteImport.update({
    id: '/dashboard/pendaftaran/',
    path: '/dashboard/pendaftaran/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPendaftaranBaruRoute =
  DashboardPendaftaranBaruRouteImport.update({
    id: '/dashboard/pendaftaran/baru',
    path: '/dashboard/pendaftaran/baru',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPendaftaranIdRoute = DashboardPendaftaranIdRouteImport.update({
  id: '/dashboard/pendaftaran/$id',
  path: '/dashboard/pendaftaran/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabang-lomba': typeof CabangLombaRoute
  '/faq': typeof FaqRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/bagan/$slug': typeof BaganSlugRoute
  '/dashboard/profil': typeof DashboardProfilRoute
  '/panitia/bracket': typeof PanitiaBracketRoute
  '/panitia/galeri': typeof PanitiaGaleriRoute
  '/panitia/idcard': typeof PanitiaIdcardRoute
  '/panitia/npsn-tools': typeof PanitiaNpsnToolsRoute
  '/panitia/sertifikat': typeof PanitiaSertifikatRoute
  '/panitia/setup': typeof PanitiaSetupRoute
  '/panitia/statistik': typeof PanitiaStatistikRoute
  '/bagan/': typeof BaganIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/panitia/': typeof PanitiaIndexRoute
  '/dashboard/pendaftaran/$id': typeof DashboardPendaftaranIdRoute
  '/dashboard/pendaftaran/baru': typeof DashboardPendaftaranBaruRoute
  '/dashboard/pendaftaran/': typeof DashboardPendaftaranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabang-lomba': typeof CabangLombaRoute
  '/faq': typeof FaqRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/bagan/$slug': typeof BaganSlugRoute
  '/dashboard/profil': typeof DashboardProfilRoute
  '/panitia/bracket': typeof PanitiaBracketRoute
  '/panitia/galeri': typeof PanitiaGaleriRoute
  '/panitia/idcard': typeof PanitiaIdcardRoute
  '/panitia/npsn-tools': typeof PanitiaNpsnToolsRoute
  '/panitia/sertifikat': typeof PanitiaSertifikatRoute
  '/panitia/setup': typeof PanitiaSetupRoute
  '/panitia/statistik': typeof PanitiaStatistikRoute
  '/bagan': typeof BaganIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/panitia': typeof PanitiaIndexRoute
  '/dashboard/pendaftaran/$id': typeof DashboardPendaftaranIdRoute
  '/dashboard/pendaftaran/baru': typeof DashboardPendaftaranBaruRoute
  '/dashboard/pendaftaran': typeof DashboardPendaftaranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabang-lomba': typeof CabangLombaRoute
  '/faq': typeof FaqRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/bagan/$slug': typeof BaganSlugRoute
  '/dashboard/profil': typeof DashboardProfilRoute
  '/panitia/bracket': typeof PanitiaBracketRoute
  '/panitia/galeri': typeof PanitiaGaleriRoute
  '/panitia/idcard': typeof PanitiaIdcardRoute
  '/panitia/npsn-tools': typeof PanitiaNpsnToolsRoute
  '/panitia/sertifikat': typeof PanitiaSertifikatRoute
  '/panitia/setup': typeof PanitiaSetupRoute
  '/panitia/statistik': typeof PanitiaStatistikRoute
  '/bagan/': typeof BaganIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/panitia/': typeof PanitiaIndexRoute
  '/dashboard/pendaftaran/$id': typeof DashboardPendaftaranIdRoute
  '/dashboard/pendaftaran/baru': typeof DashboardPendaftaranBaruRoute
  '/dashboard/pendaftaran/': typeof DashboardPendaftaranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cabang-lomba'
    | '/faq'
    | '/galeri'
    | '/jadwal'
    | '/kontak'
    | '/login'
    | '/bagan/$slug'
    | '/dashboard/profil'
    | '/panitia/bracket'
    | '/panitia/galeri'
    | '/panitia/idcard'
    | '/panitia/npsn-tools'
    | '/panitia/sertifikat'
    | '/panitia/setup'
    | '/panitia/statistik'
    | '/bagan/'
    | '/dashboard/'
    | '/panitia/'
    | '/dashboard/pendaftaran/$id'
    | '/dashboard/pendaftaran/baru'
    | '/dashboard/pendaftaran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cabang-lomba'
    | '/faq'
    | '/galeri'
    | '/jadwal'
    | '/kontak'
    | '/login'
    | '/bagan/$slug'
    | '/dashboard/profil'
    | '/panitia/bracket'
    | '/panitia/galeri'
    | '/panitia/idcard'
    | '/panitia/npsn-tools'
    | '/panitia/sertifikat'
    | '/panitia/setup'
    | '/panitia/statistik'
    | '/bagan'
    | '/dashboard'
    | '/panitia'
    | '/dashboard/pendaftaran/$id'
    | '/dashboard/pendaftaran/baru'
    | '/dashboard/pendaftaran'
  id:
    | '__root__'
    | '/'
    | '/cabang-lomba'
    | '/faq'
    | '/galeri'
    | '/jadwal'
    | '/kontak'
    | '/login'
    | '/bagan/$slug'
    | '/dashboard/profil'
    | '/panitia/bracket'
    | '/panitia/galeri'
    | '/panitia/idcard'
    | '/panitia/npsn-tools'
    | '/panitia/sertifikat'
    | '/panitia/setup'
    | '/panitia/statistik'
    | '/bagan/'
    | '/dashboard/'
    | '/panitia/'
    | '/dashboard/pendaftaran/$id'
    | '/dashboard/pendaftaran/baru'
    | '/dashboard/pendaftaran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabangLombaRoute: typeof CabangLombaRoute
  FaqRoute: typeof FaqRoute
  GaleriRoute: typeof GaleriRoute
  JadwalRoute: typeof JadwalRoute
  KontakRoute: typeof KontakRoute
  LoginRoute: typeof LoginRoute
  BaganSlugRoute: typeof BaganSlugRoute
  DashboardProfilRoute: typeof DashboardProfilRoute
  PanitiaBracketRoute: typeof PanitiaBracketRoute
  PanitiaGaleriRoute: typeof PanitiaGaleriRoute
  PanitiaIdcardRoute: typeof PanitiaIdcardRoute
  PanitiaNpsnToolsRoute: typeof PanitiaNpsnToolsRoute
  PanitiaSertifikatRoute: typeof PanitiaSertifikatRoute
  PanitiaSetupRoute: typeof PanitiaSetupRoute
  PanitiaStatistikRoute: typeof PanitiaStatistikRoute
  BaganIndexRoute: typeof BaganIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PanitiaIndexRoute: typeof PanitiaIndexRoute
  DashboardPendaftaranIdRoute: typeof DashboardPendaftaranIdRoute
  DashboardPendaftaranBaruRoute: typeof DashboardPendaftaranBaruRoute
  DashboardPendaftaranIndexRoute: typeof DashboardPendaftaranIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabang-lomba': {
      id: '/cabang-lomba'
      path: '/cabang-lomba'
      fullPath: '/cabang-lomba'
      preLoaderRoute: typeof CabangLombaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panitia/': {
      id: '/panitia/'
      path: '/panitia'
      fullPath: '/panitia/'
      preLoaderRoute: typeof PanitiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bagan/': {
      id: '/bagan/'
      path: '/bagan'
      fullPath: '/bagan/'
      preLoaderRoute: typeof BaganIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panitia/statistik': {
      id: '/panitia/statistik'
      path: '/panitia/statistik'
      fullPath: '/panitia/statistik'
      preLoaderRoute: typeof PanitiaStatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panitia/setup': {
      id: '/panitia/setup'
      path: '/panitia/setup'
      fullPath: '/panitia/setup'
      preLoaderRoute: typeof PanitiaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panitia/sertifikat': {
      id: '/panitia/sertifikat'
      path: '/panitia/sertifikat'
      fullPath: '/panitia/sertifikat'
      preLoaderRoute: typeof PanitiaSertifikatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panitia/npsn-tools': {
      id: '/panitia/npsn-tools'
      path: '/panitia/npsn-tools'
      fullPath: '/panitia/npsn-tools'
      preLoaderRoute: typeof PanitiaNpsnToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panitia/idcard': {
      id: '/panitia/idcard'
      path: '/panitia/idcard'
      fullPath: '/panitia/idcard'
      preLoaderRoute: typeof PanitiaIdcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panitia/galeri': {
      id: '/panitia/galeri'
      path: '/panitia/galeri'
      fullPath: '/panitia/galeri'
      preLoaderRoute: typeof PanitiaGaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panitia/bracket': {
      id: '/panitia/bracket'
      path: '/panitia/bracket'
      fullPath: '/panitia/bracket'
      preLoaderRoute: typeof PanitiaBracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profil': {
      id: '/dashboard/profil'
      path: '/dashboard/profil'
      fullPath: '/dashboard/profil'
      preLoaderRoute: typeof DashboardProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bagan/$slug': {
      id: '/bagan/$slug'
      path: '/bagan/$slug'
      fullPath: '/bagan/$slug'
      preLoaderRoute: typeof BaganSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pendaftaran/': {
      id: '/dashboard/pendaftaran/'
      path: '/dashboard/pendaftaran'
      fullPath: '/dashboard/pendaftaran/'
      preLoaderRoute: typeof DashboardPendaftaranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pendaftaran/baru': {
      id: '/dashboard/pendaftaran/baru'
      path: '/dashboard/pendaftaran/baru'
      fullPath: '/dashboard/pendaftaran/baru'
      preLoaderRoute: typeof DashboardPendaftaranBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pendaftaran/$id': {
      id: '/dashboard/pendaftaran/$id'
      path: '/dashboard/pendaftaran/$id'
      fullPath: '/dashboard/pendaftaran/$id'
      preLoaderRoute: typeof DashboardPendaftaranIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabangLombaRoute: CabangLombaRoute,
  FaqRoute: FaqRoute,
  GaleriRoute: GaleriRoute,
  JadwalRoute: JadwalRoute,
  KontakRoute: KontakRoute,
  LoginRoute: LoginRoute,
  BaganSlugRoute: BaganSlugRoute,
  DashboardProfilRoute: DashboardProfilRoute,
  PanitiaBracketRoute: PanitiaBracketRoute,
  PanitiaGaleriRoute: PanitiaGaleriRoute,
  PanitiaIdcardRoute: PanitiaIdcardRoute,
  PanitiaNpsnToolsRoute: PanitiaNpsnToolsRoute,
  PanitiaSertifikatRoute: PanitiaSertifikatRoute,
  PanitiaSetupRoute: PanitiaSetupRoute,
  PanitiaStatistikRoute: PanitiaStatistikRoute,
  BaganIndexRoute: BaganIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PanitiaIndexRoute: PanitiaIndexRoute,
  DashboardPendaftaranIdRoute: DashboardPendaftaranIdRoute,
  DashboardPendaftaranBaruRoute: DashboardPendaftaranBaruRoute,
  DashboardPendaftaranIndexRoute: DashboardPendaftaranIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
